<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:04:52                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoCategory extends NamedObject
	{
		protected $messages = null;
		
		/**
		 * @return CategoryMessagesDAO
		**/
		public function getMessages($lazy = false)
		{
			if (!$this->messages || ($this->messages->isLazy() != $lazy)) {
				$this->messages = new CategoryMessagesDAO($this, $lazy);
			}
			
			return $this->messages;
		}
		
		/**
		 * @return Category
		**/
		public function fillMessages($collection, $lazy = false)
		{
			$this->messages = new CategoryMessagesDAO($this, $lazy);
			
			if (!$this->id) {
				throw new WrongStateException(
					'i do not know which object i belong to'
				);
			}
			
			$this->messages->mergeList($collection);
			
			return $this;
		}
	}
?>