<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:52:04                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoMessage extends NamedObject
	{
		protected $text = null;
		protected $category = null;
		protected $author = null;
		protected $created = null;
		
		public function getText()
		{
			return $this->text;
		}
		
		/**
		 * @return Message
		**/
		public function setText($text)
		{
			$this->text = $text;
			
			return $this;
		}
		
		/**
		 * @return Category
		**/
		public function getCategory()
		{
			return $this->category;
		}
		
		/**
		 * @return Message
		**/
		public function setCategory(Category $category)
		{
			$this->category = $category;
			
			return $this;
		}
		
		/**
		 * @return Message
		**/
		public function dropCategory()
		{
			$this->category = null;
			
			return $this;
		}
		
		public function getAuthor()
		{
			return $this->author;
		}
		
		/**
		 * @return Message
		**/
		public function setAuthor($author)
		{
			$this->author = $author;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreated()
		{
			return $this->created;
		}
		
		/**
		 * @return Message
		**/
		public function setCreated(Timestamp $created)
		{
			$this->created = $created;
			
			return $this;
		}
		
		/**
		 * @return Message
		**/
		public function dropCreated()
		{
			$this->created = null;
			
			return $this;
		}
	}
?>