<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:04:52                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoCategoryDAO extends ComplexBuilderDAO
	{
		public function getTable()
		{
			return 'category';
		}
		
		public function getObjectName()
		{
			return 'Category';
		}
		
		public function getSequence()
		{
			return 'category_id';
		}
		
		public function uncacheLists()
		{
			Message::dao()->uncacheLists();
			
			return parent::uncacheLists();
		}
		
		/**
		 * @return InsertOrUpdateQuery
		**/
		public function setQueryFields(InsertOrUpdateQuery $query, Category $category)
		{
			return
				$query->
					set('id', $category->getId())->
					set('name', $category->getName());
		}
		
		/**
		 * @return Category
		**/
		protected function makeSelf(&$array, $prefix = null)
		{
			$category = new Category();
			
			$category->
				setId($array[$prefix.'id'])->
				setName($array[$prefix.'name']);
			
			return $category;
		}
	}
?>