<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:52:05                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoMessageDAO extends ComplexBuilderDAO
	{
		public function getTable()
		{
			return 'message';
		}
		
		public function getObjectName()
		{
			return 'Message';
		}
		
		public function getSequence()
		{
			return 'message_id';
		}
		
		/**
		 * @return InsertOrUpdateQuery
		**/
		public function setQueryFields(InsertOrUpdateQuery $query, Message $message)
		{
			return
				$query->
					set('id', $message->getId())->
					set('name', $message->getName())->
					set('text', $message->getText())->
					set('category_id', $message->getCategory()->getId())->
					set('author', $message->getAuthor())->
					set('created', $message->getCreated()->toString());
		}
		
		/**
		 * @return Message
		**/
		protected function makeSelf(&$array, $prefix = null)
		{
			$message = new Message();
			
			$message->
				setId($array[$prefix.'id'])->
				setName($array[$prefix.'name'])->
				setText($array[$prefix.'text'])->
				setAuthor(
					isset($array[$prefix.'author'])
						? $array[$prefix.'author']
						: null
				)->
				setCreated(new Timestamp($array[$prefix.'created']));
			
			return $message;
		}
		
		/**
		 * @return Message
		**/
		protected function makeCascade(/* Message */ $message, &$array, $prefix = null)
		{
			$message->
				setCategory(Category::dao()->getById($array[$prefix.'category_id']));
			
			return $message;
		}
		
		/**
		 * @return Message
		**/
		protected function makeJoiners(/* Message */ $message, &$array, $prefix = null)
		{
			$message->
				setCategory(
					Category::dao()->makeJoinedObject($array, Category::dao()->getJoinPrefix('category_id', $prefix))
				);
			
			return $message;
		}
	}
?>