<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:52:04                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoMessage extends AbstractProtoClass
	{
		/**
		 * @return Form
		**/
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Message')->
					setMin(PrimitiveInteger::SIGNED_MIN)->
					setMax(PrimitiveInteger::SIGNED_MAX)->
					required()
				)->
				add(
					Primitive::string('name')->
					required()->
					setMax(255)
				)->
				add(
					Primitive::string('text')->
					required()->
					setMax(2048)
				)->
				add(
					Primitive::identifier('category')->
					of('Category')->
					setMin(PrimitiveInteger::SIGNED_SMALL_MIN)->
					setMax(PrimitiveInteger::SIGNED_SMALL_MAX)->
					required()
				)->
				add(
					Primitive::string('author')->
					optional()->
					setMax(20)
				)->
				add(
					Primitive::timestamp('created')->
					required()
				);
		}
		
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::make('id', 'id', null, true, true, null, null),
				'name' => LightMetaProperty::make('name', 'name', null, true, true, null, null),
				'text' => LightMetaProperty::make('text', 'text', null, true, true, null, null),
				'category' => LightMetaProperty::make('category', 'category_id', 'Category', true, false, 'OneToOne', null),
				'author' => LightMetaProperty::make('author', 'author', null, false, true, null, null),
				'created' => LightMetaProperty::make('created', 'created', 'Timestamp', true, true, null, null)
			);
		}
	}
?>