<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:04:52                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoCategory extends AbstractProtoClass
	{
		/**
		 * @return Form
		**/
		public function makeForm()
		{
			return
				Form::create()->
				add(
					Primitive::identifier('id')->
					of('Category')->
					setMin(PrimitiveInteger::SIGNED_SMALL_MIN)->
					setMax(PrimitiveInteger::SIGNED_SMALL_MAX)->
					required()
				)->
				add(
					Primitive::string('name')->
					required()->
					setMax(255)
				);
		}
		
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::make('id', 'id', null, true, true, null, null),
				'name' => LightMetaProperty::make('name', 'name', null, true, true, null, null),
				'messages' => LightMetaProperty::make('messages', 'messages_id', 'Message', false, false, 'OneToMany', null)
			);
		}
	}
?>