<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.3.99 at 2007-09-07 23:04:52                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class CategoryMessagesDAO extends OneToManyLinked
	{
		public function __construct(Category $category, $lazy = false)
		{
			parent::__construct(
				$category,
				Message::dao(),
				$lazy
			);
		}
		
		/**
		 * @return CategoryMessagesDAO
		**/
		public static function create(Category $category, $lazy = false)
		{
			return new self($category, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'category_id';
		}
	}
?>